import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowRight,Check,Code2,Menu,Play,ShieldCheck,Sparkles,X,Zap} from 'lucide-react';
import './styles.css';

const models=[['GPT-5.2','OpenAI','$1.75 / $14'],['Claude Sonnet 4.5','Anthropic','$3 / $15'],['Gemini 2.5 Pro','Google','$1.25 / $10'],['DeepSeek V3.2','DeepSeek','$0.28 / $0.42']];
const Brand=()=> <a className="brand" href="#top"><span className="brand-mark"><img src="/runbridge-logo.png" alt=""/></span><span>runbridge<span>.ai</span></span></a>;
function App(){const [mobile,setMobile]=useState(false);const [toast,setToast]=useState(false);const notify=()=>{setToast(true);setTimeout(()=>setToast(false),2200)};const consoleUrl='http://localhost:3300';return <div className="site" id="top">
<header className="nav"><Brand/><nav className={mobile?'links open':'links'}><a href="#models" onClick={()=>setMobile(false)}>Models</a><a href="#platform" onClick={()=>setMobile(false)}>Platform</a><a href="#pricing" onClick={()=>setMobile(false)}>Pricing</a><a href="#developers" onClick={()=>setMobile(false)}>Developers</a><a href="#company" onClick={()=>setMobile(false)}>Company</a></nav><div className="nav-actions"><a href={consoleUrl}>Log in</a><button className="button small" onClick={()=>location.href=consoleUrl}>Start building <ArrowRight size={14}/></button></div><button className="menu" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button></header>
<main><section className="hero"><div className="glow"/><div className="hero-copy"><div className="kicker"><span/>THE AI GATEWAY FOR BUILDERS</div><h1>Every model.<br/><em>One reliable bridge.</em></h1><p>Runbridge gives your team one fast, observable API for the world’s best AI models—so you can ship confidently and scale without provider lock-in.</p><div className="hero-actions"><button className="button" onClick={()=>location.href=consoleUrl}>Start building free <ArrowRight size={16}/></button><button className="ghost" onClick={()=>document.getElementById('platform').scrollIntoView({behavior:'smooth'})}><Play size={15} fill="currentColor"/> See how it works</button></div><div className="proof"><span><Check size={13}/> OpenAI-compatible</span><span><Check size={13}/> No minimums</span><span><Check size={13}/> Built for production</span></div></div><div className="visual"><div className="orbit one"/><div className="orbit two"/><div className="hero-logo"><img src="/runbridge-logo.png" alt="Runbridge"/></div>{[['GPT-5.2','OpenAI','a'],['Claude 4.5','Anthropic','b'],['Gemini Pro','Google','c'],['DeepSeek','DeepSeek','d']].map(([a,b,c])=><div className={'node '+c} key={a}><span>{a}</span><small>{b}</small></div>)}</div></section>
<section className="logo-strip"><span>POWERING THE NEXT GENERATION OF AI PRODUCTS</span><div><b>OPENAI</b><b>ANTHROPIC</b><b>GOOGLE</b><b>DEEPSEEK</b><b>xAI</b></div></section>
<section className="section" id="models"><div className="intro"><div><span className="kicker plain">ONE API, EVERY POSSIBILITY</span><h2>The right model for<br/><em>every idea.</em></h2></div><p>Compare, test, and route across leading providers with one consistent interface and predictable billing.</p></div><div className="model-list">{models.map(([name,provider,price],i)=><article className="model" key={name}><div className={'model-icon i'+i}>{provider[0]}</div><div><h3>{name}</h3><p>{provider}</p></div><span className="cost">{price}<small> input / output per 1M</small></span><ArrowRight size={16}/></article>)}</div><button className="link" onClick={()=>location.href=consoleUrl}>Explore all models <ArrowRight size={15}/></button></section>
<section className="platform" id="platform"><div className="platform-copy"><span className="kicker plain">A BETTER WAY TO BUILD</span><h2>Infrastructure that<br/><em>gets out of the way.</em></h2><p>Route every request with confidence. Runbridge handles the complexity behind a single clean API so your team can focus on the product, not the plumbing.</p><div className="features"><div><span><Zap size={17}/></span><div><b>Smart routing</b><small>Balance quality, cost, and latency automatically.</small></div></div><div><span><ShieldCheck size={17}/></span><div><b>Production-grade reliability</b><small>Retries, fallbacks, and health signals built in.</small></div></div><div><span><Code2 size={17}/></span><div><b>Drop-in compatible</b><small>Switch providers without rewriting your app.</small></div></div></div></div><div className="code-card"><div className="code-top"><i/><i/><i/><small>request.js</small></div><pre><code><i>const</i> response = <i>await</i> runbridge.chat.completions.create({'{'}{`\n`}  model: <b>"gpt-5.2"</b>,{`\n`}  messages: [{`{`} role: <b>"user"</b>,{`\n`}    content: <b>"Ship it."</b> {'}'}]{`\n`}{'}'});</code></pre><div className="result"><span><Check size={12}/> 200 OK</span><small>runbridge · 742ms</small></div></div></section>
<section className="stats"><div><strong>99.94%</strong><span>request success rate</span></div><div><strong>742ms</strong><span>median global latency</span></div><div><strong>40+</strong><span>models, one API</span></div><div><strong>24/7</strong><span>built-in observability</span></div></section>
<section className="pricing section" id="pricing"><div className="intro"><div><span className="kicker plain">SIMPLE, PREDICTABLE PRICING</span><h2>Pay for what<br/><em>you use.</em></h2></div><p>No platform fees. No confusing tiers. Bring your own volume and keep your team moving.</p></div><div className="plans"><article><span className="plan-label">STARTER</span><h3>For exploring</h3><strong>$0<span>/month</span></strong><p>Everything you need to prototype your next AI product.</p><button className="secondary" onClick={notify}>Get started <ArrowRight size={14}/></button><ul><li><Check size={14}/> Pay-as-you-go credits</li><li><Check size={14}/> Every supported model</li><li><Check size={14}/> Usage dashboard</li></ul></article><article className="featured"><div className="popular">MOST POPULAR</div><span className="plan-label">SCALE</span><h3>For shipping</h3><strong>$49<span>/month</span></strong><p>Priority routing, team controls, and more room to grow.</p><button className="button" onClick={notify}>Start building <ArrowRight size={14}/></button><ul><li><Check size={14}/> Everything in Starter</li><li><Check size={14}/> Priority support & routing</li><li><Check size={14}/> Team workspaces</li></ul></article><article><span className="plan-label">ENTERPRISE</span><h3>For scaling</h3><strong>Let’s talk</strong><p>Custom limits, security, and support for your business.</p><button className="secondary" onClick={notify}>Talk to sales <ArrowRight size={14}/></button><ul><li><Check size={14}/> Dedicated infrastructure</li><li><Check size={14}/> SSO & advanced controls</li><li><Check size={14}/> SLA-backed reliability</li></ul></article></div></section>
<section className="cta" id="developers"><div><span className="kicker">READY WHEN YOU ARE</span><h2>Build the future<br/><em>from here.</em></h2><p>One key. One endpoint. Everything you need to move from idea to production.</p></div><div className="cta-actions"><button className="button light" onClick={()=>location.href=consoleUrl}>Open the console <ArrowRight size={16}/></button><button className="ghost light-text" onClick={notify}>Talk to our team <ArrowRight size={15}/></button></div></section></main>
<footer id="company"><div className="footer-main"><div><Brand/><p>The reliable AI gateway<br/>for builders.</p></div><div className="footer-links"><div><b>Product</b><a href="#models">Models</a><a href="#platform">Platform</a><a href="#pricing">Pricing</a></div><div><b>Developers</b><a href="#developers">Documentation</a><a href="#developers">API reference</a><a href="#developers">Status</a></div><div><b>Company</b><a href="#company">About</a><a href="#company">Contact</a><a href="#company">Privacy</a></div></div></div><div className="footer-bottom"><span>© 2026 Runbridge AI, Inc.</span><span>Made for teams who ship.</span></div></footer>{toast&&<div className="toast"><Check size={15}/>Thanks—we’ll be in touch.</div>}</div>}
createRoot(document.getElementById('root')).render(<App/>);
