from pathlib import Path
from html import escape as e
import re, json
from page_content import enhance
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'dist'
source=(ROOT/'templates/home.html').read_text()
head=source.split('<head>')[1].split('</head>')[0]
brand=re.search(r'<a class="brand".*?</a>',source,re.S).group(0).replace('href="#"','href="/"')
models=[
 dict(slug='gpt',name='GPT',provider='OpenAI',kind='text',icon='✳',tone='gpt',desc='General-purpose language and multimodal models for assistants, code and everyday product features.',uses=['Writing assistants','Code generation','Document workflows']),
 dict(slug='claude',name='Claude',provider='Anthropic',kind='text',icon='✳',tone='claude',desc='A model family for thoughtful writing, complex reasoning and code-focused workflows.',uses=['Coding copilots','Long-form writing','Document analysis']),
 dict(slug='gemini',name='Gemini',provider='Google',kind='text',icon='✦',tone='gemini',desc='Explore language and multimodal understanding for applications that work across different inputs.',uses=['Multimodal assistants','Knowledge tools','Content understanding']),
 dict(slug='deepseek',name='DeepSeek',provider='DeepSeek',kind='text',icon='D',tone='whisper',desc='Language and reasoning models for problem solving, useful code and text generation.',uses=['Reasoning workflows','Code assistance','Text generation']),
 dict(slug='flux',name='FLUX',provider='Black Forest Labs',kind='image',icon='F.',tone='flux',desc='Explore image creation and editing for visual products, creative tools and design workflows.',uses=['Product visuals','Creative concepts','Image editing']),
 dict(slug='gpt-image',name='GPT Image',provider='OpenAI',kind='image',icon='✳',tone='gpt',desc='A family of image models for turning creative instructions and visual references into new images.',uses=['Marketing assets','Visual prototyping','Creative applications']),
 dict(slug='seedance',name='Seedance',provider='ByteDance',kind='video',icon='▰',tone='seedance',desc='Explore video generation for visual storytelling, motion concepts and creative production.',uses=['Short-form content','Product stories','Motion concepts']),
 dict(slug='wan',name='Wan',provider='Alibaba',kind='video',icon='W',tone='gemini',desc='Video models for exploring text-to-video and image-to-video creation workflows.',uses=['Campaign videos','Visual narratives','Image animation']),
 dict(slug='sora',name='Sora',provider='OpenAI',kind='video',icon='S',tone='gpt',desc='Explore video generation for transforming scene descriptions into moving visual ideas.',uses=['Story development','Creative experiments','Video concepts'])
]
(OUT/'models.json').write_text(json.dumps(models))

def header(active=''):
 links=''.join(f'<a href="/{slug}/"'+(' aria-current="page"' if active==slug else '')+f'>{label}</a>' for slug,label in [('models','Models'),('pricing','Pricing'),('solutions','Solutions'),('enterprise','Enterprise'),('docs','Documentation'),('blog','Blog'),('changelog','Changelog'),('support','Support')])
 return f'<a class="skip-link" href="#main">Skip to content</a><div class="announcement"><span>MEET RUNBRIDGE AI</span> One bridge to every generation model. <a href="/models/">Explore models ↗</a></div><header class="header"><div class="container nav">{brand}<nav aria-label="Main navigation" id="main-nav">{links}</nav><a class="button small nav-cta" href="/docs/">Start building ↗</a><button class="menu-toggle" aria-label="Open navigation" aria-expanded="false" aria-controls="main-nav">☰</button></div></header>'

def footer():
 groups=[('Models',[('models/gpt','GPT'),('models/claude','Claude'),('models/gemini','Gemini'),('models/flux','FLUX'),('models/seedance','Seedance')]),('Developer',[('docs','Quickstart'),('docs/authentication','Authentication'),('docs/api-reference','API reference'),('integrations','Integrations')]),('Company',[('about','About RunBridge'),('platform','Platform'),('enterprise','Enterprise'),('support','Support')]),('Resources',[('models','Model catalog'),('pricing','Pricing'),('solutions','Solutions'),('blog','Blog'),('changelog','Changelog')])]
 cols=''.join('<div><h3>'+title+'</h3>'+''.join(f'<a href="/{slug}/">{label}</a>' for slug,label in links)+'</div>' for title,links in groups)
 return f'<footer class="container site-footer"><div class="footer-intro">{brand}<p>Run any AI model<br>through one bridge.</p><span>runbridge.ai</span></div><div class="footer-columns">{cols}</div><div class="footer-bottom"><span>© 2026 RunBridge AI</span><span>Unified API for image, video, and text models · Brand preview</span></div></footer><div id="toast" role="status" aria-live="polite"></div>'

def page(path,title,description,body,active=''):
 active=active or (path.parts[0] if path.parts else '')
 body=enhance(str(path),body)
 h=re.sub(r'<title>.*?</title>',f'<title>{e(title)} | RunBridge AI</title>',head)
 h=re.sub(r'<meta name="description" content="[^"]*">',f'<meta name="description" content="{e(description,quote=True)}">',h)
 h+='<link rel="stylesheet" href="/pages.css"><link rel="stylesheet" href="/navigation.css">'
 if str(path)=='models/gpt':h+='<link rel="stylesheet" href="/gpt-detail.css"><link rel="stylesheet" href="/gpt-sticky-nav-v2.css">'
 dest=OUT/path/'index.html';dest.parent.mkdir(parents=True,exist_ok=True)
 dest.write_text(f'<!doctype html><html lang="en"><head>{h}</head><body>{header(active)}<main id="main">{body}</main>{footer()}<script src="/app.js"></script><script src="/pages.js"></script></body></html>')

def hero(kicker,title,desc,extra='',cls=''):
 return f'<section class="page-hero {cls}"><div class="container"><div class="eyebrow">{kicker}</div><h1>{title}</h1><p>{desc}</p>{extra}</div></section>'
def crumb(*items):
 return '<nav class="breadcrumb container" aria-label="Breadcrumb"><a href="/">Home</a>'+''.join(f'<span>/</span><a href="{url}">{label}</a>' if url else f'<span>/</span><span aria-current="page">{label}</span>' for label,url in items)+'</nav>'
def cta(title='One bridge. Your next big idea.',desc='Bring image, video and text models into one development workflow.'):
 return f'<section class="page-cta"><div class="container"><div><h2>{title}</h2><p>{desc}</p></div><a class="button white" href="/docs/">Start building ↗</a></div></section>'
def cards(items):
 return '<div class="info-grid">'+''.join(f'<article class="info-card"><span class="eyebrow">{i+1:02d}</span><h3>{title}</h3><p>{text}</p></article>' for i,(title,text) in enumerate(items))+'</div>'
def faq(items):
 return '<section class="container content-section faq-section"><div><div class="eyebrow">A FEW THINGS TO KNOW</div><h2>Frequently asked questions</h2></div><div>'+''.join(f'<details class="faq"><summary>{q}<span>+</span></summary><p>{a}</p></details>' for q,a in items)+'</div></section>'
def modelcard(m):
 return f'<a class="model-card" href="/models/{m["slug"]}/" data-category="{m["kind"]}" data-provider="{m["provider"]}" data-name="{m["name"]}"><div class="card-top"><span class="model-icon {m["tone"]}">{m["icon"]}</span><span class="tag">{m["kind"].title()} generation</span></div><h3>{m["name"]}</h3><div class="model-provider">{m["provider"]}</div><p>{m["desc"]}</p><div class="card-bottom"><span>View model family</span><span>↗</span></div></a>'

def gpt_detail():
 versions=[
  ('gpt-5.2','GPT-5.2','Frontier','400K','128K','$1.75','$14.00','Best quality for complex agents and reasoning'),
  ('gpt-5-mini','GPT-5 mini','Fast','400K','128K','$0.25','$2.00','Fast, efficient model for high-volume workloads'),
  ('gpt-4.1','GPT-4.1','Reliable','1M','32K','$2.00','$8.00','Strong instruction following and long context'),
  ('gpt-4.1-mini','GPT-4.1 mini','Efficient','1M','32K','$0.40','$1.60','Balanced latency, intelligence and cost'),
 ]
 options=''.join(f'<option value="{mid}" data-label="{label}" data-context="{context}" data-output="{output}" data-input-price="{inp}" data-output-price="{out}">{label} · {badge}</option>' for mid,label,badge,context,output,inp,out,_ in versions)
 rows=''.join(f'<tr><td><strong>{label}</strong><span class="model-id">{mid}</span></td><td>{context}</td><td>{output}</td><td>{inp}</td><td>{out}</td><td>{purpose}</td></tr>' for mid,label,badge,context,output,inp,out,purpose in versions)
 sample='You are a concise product assistant.\n\nUser: Explain why a unified AI API is useful in three bullet points.'
 code='''from openai import OpenAI

client = OpenAI(
    api_key="YOUR_RUNBRIDGE_API_KEY",
    base_url="https://api.runbridge.ai/v1"
)

response = client.chat.completions.create(
    model="gpt-5.2",
    messages=[
        {"role": "user", "content": "Build a launch checklist."}
    ],
    temperature=0.7,
    max_tokens=1024
)

print(response.choices[0].message.content)'''
 body=crumb(('Models','/models/'),('GPT',None))
 body+=f'''<section class="container gpt-hero">
 <div class="gpt-identity"><div class="detail-provider"><span class="model-icon gpt">✳</span><span>OpenAI</span><span class="tag">Text · Vision · Tools</span></div><h1>GPT API</h1><p>OpenAI's general-purpose model family for reasoning, coding, agents, structured output and multimodal applications—available through one OpenAI-compatible endpoint.</p><div class="hero-actions"><a href="#playground" class="button">Try in Playground ↗</a><a href="#api-docs" class="button secondary">View API docs →</a></div></div>
 <aside class="gpt-version-card"><label for="gpt-version">SELECT A MODEL</label><select id="gpt-version">{options}</select><dl><div><dt>Model ID</dt><dd id="gpt-model-id">gpt-5.2</dd></div><div><dt>Context window</dt><dd id="gpt-context">400K tokens</dd></div><div><dt>Max output</dt><dd id="gpt-output">128K tokens</dd></div><div><dt>Input</dt><dd id="gpt-input-price">$1.75 / 1M</dd></div><div><dt>Output</dt><dd id="gpt-output-price">$14.00 / 1M</dd></div></dl></aside>
 </section>'''
 body+='<nav class="detail-tabs container" aria-label="GPT model sections"><a href="#overview">Overview</a><a href="#playground">Playground</a><a href="#api-docs">API docs</a><a href="#pricing">Pricing</a><a href="#models">Models</a></nav>'
 body+='''<section class="container content-section gpt-overview" id="overview"><div><div class="eyebrow">MODEL OVERVIEW</div><h2>Build production-ready AI features.</h2><p class="wide-copy">Use GPT for conversational products, software agents, code generation, data extraction and vision understanding. Choose the model per request without changing your integration.</p></div><div class="gpt-facts"><article><strong>Text + vision</strong><span>Multimodal input</span></article><article><strong>Tool calling</strong><span>Connect app functions</span></article><article><strong>Structured output</strong><span>Reliable JSON schemas</span></article><article><strong>Streaming</strong><span>Low-latency responses</span></article></div></section>'''
 body+=f'''<section class="soft-section" id="playground"><div class="container content-section"><div class="section-top"><div><div class="eyebrow">PLAYGROUND</div><h2>Test a GPT prompt.</h2></div><p>Interactive browser preview · no credits used</p></div><div class="gpt-playground">
 <form id="gpt-playground-form" class="playground-controls"><div class="playground-field"><label for="playground-model">Model</label><select id="playground-model">{options}</select></div><div class="playground-field"><label for="system-prompt">System instructions</label><textarea id="system-prompt" rows="3">You are a helpful, concise assistant.</textarea></div><div class="playground-field grow"><label for="user-prompt">User message</label><textarea id="user-prompt" rows="8">{sample}</textarea></div><div class="playground-sliders"><label>Temperature <output id="temperature-value">0.7</output><input id="temperature" type="range" min="0" max="2" step="0.1" value="0.7"></label><label>Max tokens <output id="max-tokens-value">1024</output><input id="max-tokens" type="range" min="128" max="4096" step="128" value="1024"></label></div><button class="button playground-run" type="submit">Run prompt <span>↗</span></button></form>
 <div class="playground-response"><div class="response-bar"><span>ASSISTANT RESPONSE</span><span id="playground-status">Ready</span></div><div id="playground-empty"><span class="response-spark">✳</span><h3>Ready when you are.</h3><p>Configure the prompt and run this local preview.</p></div><div id="playground-result" hidden><div class="response-message" id="playground-answer"></div><div class="response-meta"><span id="playground-used-model">gpt-5.2</span><span id="playground-token-estimate">— tokens</span><span id="playground-latency">— s</span></div></div></div>
 </div><div class="notice">This Playground simulates the product experience in your browser. It does not send your prompt to OpenAI or RunBridge and does not consume API credits.</div></div></section>'''
 body+=f'''<section class="container content-section" id="api-docs"><div class="section-top"><div><div class="eyebrow">API DOCUMENTATION</div><h2>One familiar request format.</h2></div><p>OpenAI-compatible Chat Completions API</p></div><div class="gpt-docs"><aside><a href="#quickstart" class="active">Quickstart</a><a href="#request-fields">Request fields</a><a href="#response-format">Response</a><a href="/docs/authentication/">Authentication ↗</a><a href="/docs/errors/">Errors & retries ↗</a></aside><div><h3 id="quickstart">Python quickstart</h3><p>Install the OpenAI SDK, point it to the RunBridge endpoint and use the exact model ID shown above.</p><div class="plain-code code-with-action"><button type="button" data-copy-target="gpt-code">Copy</button><pre id="gpt-code">{e(code)}</pre></div><h3 id="request-fields">Core request fields</h3><div class="table-scroll"><table class="pricing-table doc-fields"><thead><tr><th>Field</th><th>Type</th><th>Description</th></tr></thead><tbody><tr><td>model</td><td>string</td><td>Required. Exact GPT model ID.</td></tr><tr><td>messages</td><td>array</td><td>Ordered system, user and assistant messages.</td></tr><tr><td>temperature</td><td>number</td><td>Controls response variation from 0 to 2.</td></tr><tr><td>max_tokens</td><td>integer</td><td>Maximum generated output tokens.</td></tr><tr><td>stream</td><td>boolean</td><td>Returns incremental server-sent events when true.</td></tr></tbody></table></div><h3 id="response-format">Response shape</h3><div class="plain-code"><pre>{{
  "id": "chatcmpl_...",
  "model": "gpt-5.2",
  "choices": [{{
    "message": {{"role": "assistant", "content": "..."}},
    "finish_reason": "stop"
  }}],
  "usage": {{"prompt_tokens": 24, "completion_tokens": 91}}
}}</pre></div></div></div></section>'''
 body+=f'''<section class="soft-section" id="pricing"><div class="container content-section"><div class="section-top"><div><div class="eyebrow">GPT PRICING</div><h2>Compare cost and capability.</h2></div><p>USD per 1 million tokens</p></div><div class="table-scroll"><table class="pricing-table gpt-price-table"><thead><tr><th>Model</th><th>Context</th><th>Max output</th><th>Input</th><th>Output</th><th>Best for</th></tr></thead><tbody>{rows}</tbody></table></div><p class="pricing-disclaimer">Reference rates for planning, last reviewed September 2026. Cached input, tools and special capabilities may use different billing units. Confirm the current RunBridge rate in your account before production use.</p></div></section>'''
 body+='''<section class="container content-section" id="models"><div class="section-top"><div><div class="eyebrow">AVAILABLE MODELS</div><h2>Pick the right GPT for the job.</h2></div></div><div class="info-grid"><article class="info-card"><span class="tag">FRONTIER</span><h3>GPT-5.2</h3><p>Choose for demanding reasoning, complex code and multi-step agent workflows.</p></article><article class="info-card"><span class="tag">HIGH VOLUME</span><h3>GPT-5 mini</h3><p>Choose for responsive applications that need strong quality at lower cost.</p></article><article class="info-card"><span class="tag">LONG CONTEXT</span><h3>GPT-4.1</h3><p>Choose for reliable instruction following and very large documents.</p></article></div></section>'''+cta('Start building with GPT.','Use one RunBridge key and an OpenAI-compatible request format.')
 return body

# Keep the approved home design, with real page navigation and detail links.
home=source.split('<main>')[1].split('</main>')[0]
for old,new in [('#developers','/docs/'),('#models','/models/'),('#platform','/platform/'),('#pricing','/pricing/')]:home=home.replace('href="'+old+'"','href="'+new+'"')
for m in models:
 pattern=r'<button class="model-card"([^>]*data-model="'+re.escape(m['name'])+r'"[^>]*)>(.*?)</button>'
 home=re.sub(pattern,lambda match:'<a class="model-card" href="/models/'+m['slug']+'/"'+match.group(1)+'>'+match.group(2).replace('Explore model family','View model family')+'</a>',home,flags=re.S)
home=home.replace('</div><p class="model-footnote">','</div><div class="center-action"><a class="text-link" href="/models/">View all model families →</a></div><p class="model-footnote">')
page(Path(''),'Run any AI model through one bridge.','Unified API for image, video, and text models.',home)

# Catalog: search, capability/provider filters, sorting, cards and empty state.
filters=''.join(f'<label class="check-row"><input type="checkbox" name="provider" value="{p}"><span>{p}</span></label>' for p in sorted(set(m['provider'] for m in models)))
body=hero('ONE API, EVERY MODEL','Explore the RunBridge<br><span>model catalog.</span>','Find your next text, image or video model. Explore each family, review its use cases and plan your integration.','<label class="search-field"><span>⌕</span><input type="search" id="model-search" placeholder="Search models, providers or capabilities…" aria-label="Search models"></label><div class="hero-pills"><span>9 model families</span><span>Image · Video · Text</span><span>One unified API</span></div>')
body+=f'<section class="container catalog-layout"><aside class="catalog-sidebar"><div class="aside-title"><h2>Filters</h2><button id="reset-filters" class="text-button">Reset</button></div><fieldset><legend>Model type</legend>'+''.join(f'<label class="check-row"><input type="radio" name="capability" value="{v}" '+('checked' if v=='all' else '')+f'><span>{l}</span></label>' for v,l in [('all','All models'),('text','Text & reasoning'),('image','Image generation'),('video','Video generation')])+f'</fieldset><fieldset><legend>Providers</legend>{filters}</fieldset><div class="sidebar-note">Explore model families here. Exact versions and launch availability will be confirmed in the live catalog.</div></aside><div class="catalog-results"><div class="results-toolbar"><span id="result-count" aria-live="polite">9 model families</span><label>Sort <select id="model-sort"><option value="featured">Featured</option><option value="az">Name: A–Z</option><option value="za">Name: Z–A</option></select></label></div><div class="model-grid catalog-grid">'+''.join(modelcard(m) for m in models)+'</div><div id="no-results" class="empty-state" hidden><h3>No models match your search.</h3><p>Try a different term or clear the filters.</p><button class="button" id="empty-reset">Clear filters</button></div></div></section>'+cta()
page(Path('models'),'AI model catalog','Explore image, video and text model families.',body,'models')

# Model detail layout: overview, sticky section navigation, integration and related models.
for m in models:
 if m['slug']=='gpt':
  page(Path('models')/m['slug'],'GPT API, playground, docs & pricing',m['desc'],gpt_detail(),'models')
  continue
 capabilities={'text':['Text generation','Reasoning workflows','Code assistance'],'image':['Image generation','Visual ideation','Creative workflows'],'video':['Video generation','Motion concepts','Visual storytelling']}[m['kind']]
 body=crumb(('Models','/models/'),(m['name'],None))
 body+=f'<section class="container detail-hero"><div><div class="detail-provider"><span class="model-icon {m["tone"]}">{m["icon"]}</span><span>{m["provider"]}</span><span class="tag">{m["kind"].title()} model family</span></div><h1>{m["name"]} API</h1><p>{m["desc"]}</p><div class="hero-actions"><a href="/docs/" class="button">View API quickstart ↗</a><a href="/pricing/" class="button secondary">Explore pricing →</a></div></div><aside class="detail-summary"><div class="eyebrow">INTEGRATION AT A GLANCE</div><dl><div><dt>Provider</dt><dd>{m["provider"]}</dd></div><div><dt>Output</dt><dd>{m["kind"].title()}</dd></div><div><dt>Model version</dt><dd>Select at launch</dd></div><div><dt>Usage rates</dt><dd>To be announced</dd></div></dl><p>Capabilities and request parameters vary by model version.</p></aside></section>'
 body+='<nav class="detail-tabs container" aria-label="Model sections">'+''.join(f'<a href="#{slug}">{label}</a>' for slug,label in [('overview','Overview'),('capabilities','Capabilities'),('use-cases','Use cases'),('api','API'),('pricing','Pricing'),('related','Other models')])+'</nav>'
 body+=f'<section class="container content-section" id="overview"><div class="section-top"><div><div class="eyebrow">OVERVIEW</div><h2>Build with {m["name"]}.</h2></div><p>One family. A range of creative possibilities.</p></div><p class="wide-copy">{m["desc"]} Start with a representative task, compare outputs against your quality requirements, and choose the exact model version that fits your application. The family overview helps you plan; the selected version defines supported inputs, limits and billing.</p></section>'
 body+='<section class="soft-section" id="capabilities"><div class="container content-section"><div class="eyebrow">CAPABILITIES</div><h2>A starting point for your workflow.</h2>'+cards([(x,'Evaluate this workflow with the specific model version you choose. Input formats and supported parameters can differ.') for x in capabilities])+'</div></section>'
 body+='<section class="container content-section" id="use-cases"><div class="eyebrow">USE CASES</div><h2>From model to product.</h2>'+cards([(x,{'text':'Connect generation to your own context, review process and application tools.','image':'Define a visual brief, generate candidates and review the output before using it.','video':'Start with a short scene, set creative constraints and review the generated clip.'}[m['kind']]) for x in m['uses']])+'</section>'
 body+=f'<section class="container detail-api content-section" id="api"><div><div class="eyebrow">API INTEGRATION</div><h2>Keep your connection simple.</h2><p>Choose the exact model ID from your account catalog and use the matching request format. Text, image and video requests have different schemas.</p><a class="text-link" href="/docs/api-reference/">Open the API guide →</a></div><div class="plain-code"><span>CONFIGURATION</span><pre>RUNBRIDGE_API_KEY=your_account_key\nRUNBRIDGE_BASE_URL=your_account_endpoint\nRUNBRIDGE_MODEL=your_selected_model_id</pre><p>Values are account-specific. This preview does not make live API calls.</p></div></section>'
 body+='<section class="soft-section" id="pricing"><div class="container content-section compact-split"><div><div class="eyebrow">PRICING</div><h2>Know the unit before you scale.</h2><p>Check the selected version’s input and output rates, generation settings and billing unit before estimating usage.</p></div><a class="button secondary" href="/pricing/">Open budget estimator →</a></div></section>'
 related=[x for x in models if x['slug']!=m['slug'] and x['kind']==m['kind']][:3]
 if len(related)<2:related=[x for x in models if x['slug']!=m['slug']][:3]
 body+='<section class="container content-section" id="related"><div class="section-top"><h2>Keep exploring.</h2><a class="text-link" href="/models/">All models →</a></div><div class="model-grid">'+''.join(modelcard(x) for x in related)+'</div></section>'+cta()
 page(Path('models')/m['slug'],m['name']+' API',m['desc'],body,'models')

# Pricing: the reference layout, with honest launch status and editable planning rates.
body=hero('RUNBRIDGE AI PRICING','A clearer view of<br><span>your AI budget.</span>','Understand the billing unit, estimate your workload, and choose the right model for every request.','<div class="hero-pills"><span>Text tokens</span><span>Image generation</span><span>Video duration</span></div>')
body+='<section class="container content-section"><div class="section-top"><div><div class="eyebrow">BILLING FRAMEWORK</div><h2>Different outputs. Clear units.</h2></div><p>Review each model’s rate before sending a request.</p></div>'+cards([('Text & reasoning','Input and output tokens may have different rates. Cached inputs and optional capabilities can have their own billing rules.'),('Image generation','Rates may depend on tokens, image count, resolution or quality. Compare models using the same output settings.'),('Video generation','Rates may depend on duration, resolution and request options. Account for generation settings when planning a budget.')])+'</section>'
body+='<section class="soft-section"><div class="container content-section"><div class="section-top"><div><div class="eyebrow">BUDGET ESTIMATOR</div><h2>Make room for your next idea.</h2></div><span class="preview-label">Planning tool · not a price quote</span></div><div class="estimator"><div class="budget-input"><label for="budget">Monthly budget</label><div class="currency-input"><span>$</span><input id="budget" type="number" min="1" max="1000000" value="100" step="1"></div><label class="sr-only" for="budget-range">Adjust monthly budget</label><input id="budget-range" type="range" min="10" max="5000" step="10" value="100"><div class="range-labels"><span>$10</span><span>$5,000</span></div><p>Each result assumes the entire budget goes to that one output type. Edit the example rates to match your chosen model.</p></div><div class="estimate-results">'+''.join(f'<div class="estimate-result"><div class="eyebrow">{label}</div><output id="estimate-{kind}">—</output><span>{unit}</span><label for="rate-{kind}">Example rate: $ / {rateunit}</label><input id="rate-{kind}" type="number" min="0.0001" max="1000000" step="any" value="{rate}"></div>' for kind,label,unit,rateunit,rate in [('text','TEXT','input tokens','1M input tokens',1),('image','IMAGE','images','image',0.04),('video','VIDEO','seconds','second',0.08)])+'</div></div><p class="model-footnote">Illustrative rates only. Text estimates exclude output-token charges. RunBridge launch rates have not been announced.</p></div></section>'
body+='<section class="container content-section"><div class="section-top"><div><div class="eyebrow">MODEL PRICING</div><h2>Explore by generation type.</h2></div><p>Final prices will appear with the launch catalog.</p></div><div class="pill-tabs" role="group" aria-label="Pricing category">'+''.join(f'<button data-price-kind="{x}" aria-pressed="'+('true' if x=='text' else 'false')+f'">{x.title()} models</button>' for x in ['text','image','video'])+'</div><div class="table-scroll"><table class="pricing-table"><thead><tr><th>Model family</th><th>Provider</th><th>Billing basis</th><th>RunBridge rate</th><th></th></tr></thead><tbody>'+''.join(f'<tr data-price-row="{m["kind"]}"'+(' hidden' if m['kind']!='text' else '')+f'><td><a href="/models/{m["slug"]}/"><span class="table-icon {m["tone"]}">{m["icon"]}</span>{m["name"]}</a></td><td>{m["provider"]}</td><td>'+{'text':'Input / output tokens','image':'Model-specific image or token units','video':'Model-specific duration or request units'}[m['kind']]+f'</td><td><span class="muted">At launch</span></td><td><a href="/models/{m["slug"]}/" aria-label="View {m["name"]}">↗</a></td></tr>' for m in models)+'</tbody></table></div></section>'
body+='<section class="container enterprise-band"><div><div class="eyebrow">FOR TEAMS</div><h2>Plan for the way you grow.</h2><p>Define your model mix, workload, budget and support requirements in one project brief.</p></div><a class="button" href="/enterprise/">Explore enterprise →</a></section>'+faq([('Are these the final RunBridge prices?','No. The estimator uses editable example rates for planning. Commercial rates and billing terms will be published with the launch catalog.'),('How should I estimate text costs?','Calculate input and output tokens separately using their respective rates. Add any model-specific charges and allow room for retries or longer responses.'),('Can I compare image and video costs directly?','Only after aligning output settings. Resolution, duration, quality and supported inputs can materially affect the cost of a generation.')])+cta()
page(Path('pricing'),'Pricing & budget estimator','Plan text, image and video workloads with an editable budget estimator.',body,'pricing')

solutions=[('creative-production','Creative production','From a brief to a complete campaign.','Combine text, image and video models in one creative workflow.','image',['Draft the concept','Develop the visual direction','Bring the story into motion'],['Turn your campaign brief into scripts, headlines and scene descriptions.','Generate visual candidates and refine your direction before production.','Create short clips, review them with your team and assemble the final campaign.']),('software-and-agents','Software & agents','Put intelligence inside your product.','Build copilots and agent workflows around the model that fits each task.','text',['Define the task','Connect your context','Evaluate the result'],['Start with a narrow outcome such as answering a question or producing a code change.','Give your application the relevant knowledge, permissions and tools for that task.','Measure task success, latency and cost on examples from your actual workload.']),('ecommerce','E-commerce','Build a better product story.','Connect catalog copy, product visuals and campaign concepts through one model layer.','image',['Enrich the catalog','Create visual candidates','Produce campaign variants'],['Draft consistent descriptions from product information and your brand guidelines.','Explore image ideas while checking product accuracy and visual consistency.','Adapt approved concepts into text and video variants for different placements.'])]
body=hero('SOLUTIONS BY MODEL CAPABILITY','The right AI for<br><span>the work you do.</span>','Start with a capability. Combine models around a real workflow. Keep your product moving as the ecosystem evolves.','<div class="hero-actions"><a href="/enterprise/" class="button">Plan your project ↗</a><a href="#industries" class="button secondary">Explore solutions ↓</a></div>')
body+='<section class="container content-section"><div class="eyebrow">START WITH THE MODEL SCENARIO</div><h2>Choose the capability.<br>Connect the workflow.</h2>'+cards([('Language & reasoning','Draft, summarize and organize information. Add your own context and review process to make the output useful.'),('Vision & image','Explore visual concepts and image generation workflows, with the selected model defining inputs and editing options.'),('Video generation','Turn scene briefs into motion concepts. Build review and iteration into the creative process.')])+'</section><section class="soft-section" id="industries"><div class="container content-section"><div class="section-top"><div><div class="eyebrow">SOLUTIONS BY INDUSTRY</div><h2>From first use case<br>to your next product.</h2></div></div><div class="solution-grid">'
for slug,label,title,desc,kind,steps,details in solutions:
 body+=f'<a class="solution-card" href="/solutions/{slug}/"><span class="solution-number">0{solutions.index((slug,label,title,desc,kind,steps,details))+1} / {label.upper()}</span><h3>{title}</h3><p>{desc}</p><div class="solution-tags"><span>Text</span><span>'+('Image</span><span>Video' if kind=='image' else 'Reasoning</span><span>Code')+'</span></div><span class="text-link">Explore solution →</span></a>'
body+='</div></div></section>'+cta('Turn your next use case into a working plan.')
page(Path('solutions'),'AI solutions','Explore creative production, software and e-commerce workflows.',body,'solutions')
for slug,label,title,desc,kind,steps,details in solutions:
 body=crumb(('Solutions','/solutions/'),(label,None))+hero(label.upper(),title,desc,'<div class="hero-actions"><a class="button" href="/enterprise/">Plan this workflow ↗</a><a class="button secondary" href="/models/?type='+kind+'">Explore relevant models →</a></div>')
 body+='<section class="container content-section"><div class="eyebrow">THE WORKFLOW</div><h2>Three steps from idea to output.</h2>'+cards(list(zip(steps,details)))+'</section><section class="soft-section"><div class="container content-section"><div class="section-top"><h2>Models to explore.</h2><a class="text-link" href="/models/">Full catalog →</a></div><div class="model-grid">'+''.join(modelcard(x) for x in [m for m in models if m['kind']==kind][:3])+'</div></div></section>'+faq([('Where should we start?','Choose one repeatable task and assemble representative inputs. Define what a useful output looks like before comparing models.'),('What should we measure?','Measure task completion and output quality alongside latency and cost. Review failure cases and decide when a person should approve the output.')])+cta()
 page(Path('solutions')/slug,label+' solutions',desc,body,'solutions')

# Enterprise follows the reference's hero + form, feature rows, stakeholder cards and FAQ.
form='<form id="enterprise-form" class="brief-form"><div class="eyebrow">YOUR NEXT AI PROJECT</div><h2>Let’s map the right fit.</h2><label>Company name <input name="company" required maxlength="120" autocomplete="organization" placeholder="Acme Inc."></label><label>Work email <input name="email" type="email" required autocomplete="email" placeholder="you@company.com"></label><label>Company size <select name="size"><option>1–10 people</option><option>11–50 people</option><option>51–200 people</option><option>201–1,000 people</option><option>1,000+ people</option></select></label><label>What would you like to build? <textarea name="project" required maxlength="2000" rows="4" placeholder="Your use case, models, expected volume and timeline"></textarea></label><button class="button" type="submit">Prepare project brief ↗</button><p class="form-note">Preview: creates a brief in this page. Your details are not sent or stored.</p><div id="brief-result" hidden><h3>Your project brief is ready</h3><pre id="brief-text"></pre><button type="button" class="button secondary" id="copy-brief">Copy brief</button></div></form>'
body='<section class="enterprise-hero container"><div><div class="eyebrow">ENTERPRISE AI INFRASTRUCTURE</div><h1>One model layer.<br><span>More room to grow.</span></h1><p>Bring your teams, workflows and model requirements into one integration plan. Build an AI strategy that can evolve with your business.</p><div class="hero-pills"><span>Multi-model access</span><span>One integration plan</span><span>Team workflows</span></div><a class="text-link" href="#enterprise-benefits">Explore the approach ↓</a></div>'+form+'</section>'
body+='<section class="soft-section" id="enterprise-benefits"><div class="container content-section"><div class="eyebrow">THE UNIFIED MODEL LAYER</div><h2>A shared foundation for your AI work.</h2>'+cards([('Choice across providers','Evaluate different model families without tying your product strategy to a single provider.'),('A clear workload plan','Bring model selection, output quality, usage volume and cost assumptions into the same conversation.'),('An integration that evolves','Start with one workflow and extend it as your team discovers new use cases.')])+'</div></section>'
body+='<section class="container content-section"><div class="eyebrow">BUILT AROUND YOUR TEAM</div><h2>Different roles. One shared plan.</h2>'+cards([('Product & engineering','Define task success, model requirements, integration boundaries and a practical launch path.'),('Operations & finance','Map expected usage, billing units, budget assumptions and reporting needs.'),('Security & technical leaders','Document data handling, access requirements, regional constraints and operational expectations before launch.')])+'</section>'+faq([('Can we request custom commercial terms?','Include volume, support and contractual requirements in your project brief. RunBridge enterprise terms and availability are not finalized in this preview.'),('Does this form send a sales request?','No. It prepares a copyable brief locally in your browser. A sales submission endpoint has not been connected.'),('Where can we review integration details?','Start with the developer quickstart and API request guide. Production endpoints and account credentials will be provided separately.')])+cta()
page(Path('enterprise'),'Enterprise AI','Plan your enterprise model access, workflows and integration requirements.',body,'enterprise')

# Developer documentation: independent pages with a common left navigation.
doc_nav=[('','Quickstart'),('authentication','Authentication'),('api-reference','API request guide'),('errors','Errors & retries')]
code_panel=re.search(r'<div class="code-panel">.*?</div></div></section>',source,re.S).group(0).removesuffix('</div></section>')
def docs(title,slug,content):
 sidebar='<aside class="docs-sidebar"><span class="eyebrow">DEVELOPER DOCS</span><h2>Build with RunBridge</h2>'+''.join(f'<a href="/docs/{s+"/" if s else ""}"'+(' aria-current="page"' if s==slug else '')+f'>{label}</a>' for s,label in doc_nav)+'<div class="sidebar-note">One bridge to every generation model.</div><a href="/models/">Explore model catalog ↗</a></aside>'
 page(Path('docs')/slug,title,title+' for RunBridge AI.',crumb(('Documentation','/docs/'),(title,None))+'<div class="container docs-layout">'+sidebar+'<article class="docs-article"><div class="eyebrow">RUNBRIDGE AI DOCUMENTATION</div><h1>'+title+'</h1>'+content+'</article></div>')
docs('Your first request','', '<p class="lead">One bridge to every generation model. Start with a familiar SDK and an account-specific endpoint.</p><div class="notice">This is an integration preview. Live account creation and API credentials are not connected to this site.</div><h2>1. Prepare your configuration</h2><p>You will need an API key, a base URL and the exact model ID from your provisioned account. Keep credentials on your server.</p><div class="plain-code"><pre>RUNBRIDGE_API_KEY=your_account_key\nRUNBRIDGE_BASE_URL=your_account_endpoint\nRUNBRIDGE_MODEL=your_selected_model_id</pre></div><h2>2. Choose a client</h2><p>The examples below use an OpenAI-compatible chat request. Verify the selected model’s supported parameters before sending a live call.</p>'+code_panel+'<h2>3. Review the response</h2><p>Check the returned content and usage fields. Record your request identifier, model version and timing so you can investigate failures and compare runs.</p><h2>4. Move beyond text</h2><p>Image and video models have different inputs, settings and output lifecycles. Use the selected model’s documented schema instead of sending every workload to the chat endpoint.</p><div class="doc-next"><a href="/docs/authentication/">Next: authentication →</a></div>')
docs('Authentication','authentication','<p class="lead">Treat your API key as a server credential.</p><h2>Configure your application</h2><p>Load the key from an environment variable or your server’s secret manager. Your SDK will attach it to the authorization header.</p><div class="plain-code"><pre>Authorization: Bearer YOUR_API_KEY</pre></div><h2>Keep secrets out of the client</h2><p>Do not place a live key in browser JavaScript, public repositories, screenshots or client-side mobile bundles. Route application requests through a server you control.</p><h2>Rotate a compromised key</h2><p>Revoke the exposed credential in the account system, create a replacement and update your server configuration. Review recent usage for unexpected requests.</p><h2>Account-specific configuration</h2><p>Use the endpoint and model identifier provided for your RunBridge account. Do not assume that a model family name is a valid API model ID.</p><div class="doc-next"><a href="/docs/api-reference/">Next: API request guide →</a></div>')
docs('API request guide','api-reference','<p class="lead">Match the request to the kind of output you need.</p><div class="notice">Request patterns below explain the integration approach. Final endpoint paths and supported parameters depend on the RunBridge launch API.</div><h2>Text generation</h2><p>An OpenAI-compatible chat request uses a model identifier and an ordered messages array. Streaming and tool support depend on the selected version.</p><div class="plain-code"><pre>{\n  "model": "YOUR_MODEL_ID",\n  "messages": [\n    { "role": "user", "content": "Write a product introduction." }\n  ]\n}</pre></div><h2>Image generation</h2><p>Choose an image model and provide a creative prompt. Check the model’s supported image sizes, input-image format, quality options and output format. Billing may be token-based or output-based.</p><h2>Video generation</h2><p>A video request may start an asynchronous job. If the endpoint returns a job identifier, follow its documented polling or callback flow. Store the identifier so a page reload does not trigger a duplicate job.</p><h2>Common request considerations</h2>'+cards([('Model identifier','Use the exact version ID from the catalog, not a display name.'),('Input compatibility','Validate file type, dimensions, prompt length and parameters against the model schema.'),('Response lifecycle','Handle immediate responses, streaming events and asynchronous jobs according to the endpoint.')])+'<div class="doc-next"><a href="/docs/errors/">Next: errors & retries →</a></div>')
docs('Errors & retries','errors','<p class="lead">Make failures understandable and retries deliberate.</p><div class="table-scroll"><table class="pricing-table"><thead><tr><th>Signal</th><th>What to check</th><th>Next step</th></tr></thead><tbody>'+''.join(f'<tr><td>{a}</td><td>{b}</td><td>{c}</td></tr>' for a,b,c in [('400','Request schema or unsupported parameter','Correct the request before retrying.'),('401 / 403','Credential or access permissions','Check the account and model access.'),('429','Rate or capacity limit','Respect Retry-After if present; use backoff.'),('5xx','Service or upstream failure','Retry with bounded backoff when safe.'),('Timeout','Unknown request outcome','Check job or request status before resubmitting.')])+'</tbody></table></div><h2>Avoid duplicate generation</h2><p>A timeout does not prove that no work was started. For asynchronous jobs, check the recorded job identifier before creating another request. Use an idempotency mechanism only if the endpoint explicitly supports it.</p><h2>Keep enough context to investigate</h2><p>Record the timestamp, model ID, HTTP status and request ID. Remove API keys and sensitive input content from logs and support reports.</p><div class="doc-next"><a href="/support/">Open support guide →</a></div>')

articles=[('choose-a-generation-model','Guide','How to choose a generation model','Start with a task, define quality, and compare like-for-like.', [('Start with an outcome','Write down what the user needs to accomplish. A support reply, product image and short video need different evaluation criteria. Pick a specific task before comparing model names.'),('Build a small evaluation set','Use representative inputs from your product. Include straightforward requests, ambiguous instructions and cases where the model should fail gracefully. Keep inputs consistent across candidates.'),('Compare the whole experience','Review output quality, request latency, supported inputs and estimated cost together. For images and video, align resolution and generation settings before comparing results.'),('Keep a versioned decision','Record the model version, prompt, settings and evaluation date. Repeat the evaluation when a relevant model changes or your product requirements shift.')]),('plan-your-ai-budget','Cost planning','A practical way to plan your AI budget','Understand billing units before estimating monthly spend.', [('Start with workload volume','Estimate successful user tasks per month and the average number of model calls per task. Allow for user iteration and failed requests according to your actual billing rules.'),('Separate the units','For text, track input and output tokens separately. For image and video, identify whether the endpoint bills by tokens, output count, duration or another unit.'),('Make assumptions explicit','Keep the chosen model, rate, output settings and expected volume together. Use ranges when your workload is not yet measured. The pricing-page estimator is a starting point, not a quote.'),('Compare estimates with usage','Once your account is live, compare estimates against actual usage records. Review outliers and expensive flows before setting product limits or customer pricing.')]),('design-a-multimodal-workflow','Development','Designing a text-to-image-to-video workflow','Connect creative stages while keeping review in the loop.', [('Define the creative brief','Begin with audience, message, visual direction and output constraints. Use text generation to create structured scene descriptions that can be reviewed before image production.'),('Review the image stage','Generate candidates and check the important details. Keep the approved image together with its prompt, version and settings so the next stage has clear context.'),('Manage video as a job','Video generation can take longer than an interactive text request. Design progress states around actual job status, and make refreshes recover the existing job rather than create a duplicate.'),('Measure the final output','Evaluate the completed asset against the original brief. Track review time and iteration count as well as model cost; a cheap generation is not always a cheap finished asset.')])]
body=hero('THE RUNBRIDGE JOURNAL','Ideas for what<br><span>you build next.</span>','Practical guides for model selection, generation workflows and more predictable AI development.')
body+='<section class="container content-section"><div class="pill-tabs" role="group" aria-label="Article category">'+''.join(f'<button data-blog-filter="{v}" aria-pressed="'+('true' if v=='all' else 'false')+f'">{l}</button>' for v,l in [('all','All'),('Guide','Guides'),('Cost planning','Cost planning'),('Development','Development')])+'</div><div class="article-grid">'
for i,(slug,cat,title,desc,sections) in enumerate(articles):
 body+=f'<a class="article-card" href="/blog/{slug}/" data-article-category="{cat}"><div class="article-cover cover-{i}"><span>RUNBRIDGE / FIELD NOTES</span><strong>'+['Choose.<br>Test.<br>Build.','Know your<br>unit.<br>Own your budget.','Text.<br>Image.<br>Action.'][i]+f'</strong><b>0{i+1} ↗</b></div><div class="article-info"><span class="eyebrow">{cat}</span><h2>{title}</h2><p>{desc}</p><div class="article-meta">RunBridge AI <span>2 min read</span></div></div></a>'
body+='</div></section>'+cta()
page(Path('blog'),'Blog & guides','Practical guides for building with generation models.',body)
for slug,cat,title,desc,sections in articles:
 content=crumb(('Blog','/blog/'),(title,None))+'<article class="container article-layout"><header><div class="eyebrow">'+cat+'</div><h1>'+title+'</h1><p class="lead">'+desc+'</p><div class="article-meta">RunBridge AI · Field notes <span>2 min read</span></div></header><div class="article-body">'+''.join(f'<section id="section-{i}"><h2>{t}</h2><p>{p}</p></section>' for i,(t,p) in enumerate(sections))+'<div class="notice">Explore the <a href="/models/">model catalog</a>, <a href="/pricing/">budget estimator</a> and <a href="/docs/">developer quickstart</a> to put this into practice.</div></div><aside class="article-toc"><span class="eyebrow">IN THIS ARTICLE</span>'+''.join(f'<a href="#section-{i}">{t}</a>' for i,(t,p) in enumerate(sections))+'</aside></article>'+cta()
 page(Path('blog')/slug,title,desc,content)

body=hero('INTEGRATIONS','Keep your stack.<br><span>Expand your possibilities.</span>','Use a familiar client or workflow builder. Configure your account endpoint, API key and selected model in the right place.')
body+='<section class="container content-section"><div class="integration-grid">'+''.join(f'<article class="info-card"><span class="integration-icon">{symbol}</span><h2>{name}</h2><p>{desc}</p><a class="text-link" href="{link}">{action} →</a></article>' for symbol,name,desc,link,action in [('Py','Python','Start with the Python SDK example and server-side environment variables.','/docs/','Open Python quickstart'),('JS','JavaScript','Use the server-side JavaScript example to configure an OpenAI-compatible client.','/docs/?lang=javascript','Open JavaScript quickstart'),('>_','cURL','Inspect the request format directly from your terminal.','/docs/?lang=curl','Open cURL example'),('n8n','n8n & automation','Use an HTTP request step for the endpoint you choose; validate authentication and response handling.','/docs/api-reference/','Review request patterns'),('D','Dify & app builders','Check whether your chosen builder supports custom endpoints and the model’s request schema.','/docs/authentication/','Review configuration'),('{}','Your own application','Keep model access in your backend and handle errors at the application boundary.','/docs/errors/','Plan error handling')])+'</div><div class="notice">These are integration approaches, not certified partnerships. Tool support and configuration options should be verified against the version you use.</div></section>'+cta()
page(Path('integrations'),'Integrations','Connect your development stack to RunBridge AI.',body)
body=hero('WHY RUNBRIDGE AI','Your product comes first.<br><span>The model is your choice.</span>','A unified API approach for image, video and text workflows. One bridge to every generation model.')
body+='<section class="container content-section">'+cards([('One connection model','Keep account configuration and request handling in a consistent place in your application.'),('Choice as models evolve','Evaluate providers on the task that matters to your users and keep version changes deliberate.'),('Clear integration boundaries','Separate model access from product logic so your own workflows remain easier to maintain.')])+'</section>'+cta()
page(Path('platform'),'Why RunBridge AI','A unified model layer for your application.',body)
body=hero('ABOUT RUNBRIDGE AI','A bridge between<br><span>ideas and generation.</span>','Run any AI model through one bridge.')
body+='<section class="container content-section about-grid"><h2>More possibilities.<br>Less integration overhead.</h2><div><p>RunBridge AI is a new brand for a unified API experience across image, video and text models. The goal is simple: give developers a consistent place to connect generation capabilities to the products they build.</p><p>Our product direction centers on model choice, familiar integration patterns and clearer workload planning. This site introduces the brand and the planned developer experience.</p><a class="text-link" href="/platform/">Explore the platform approach →</a></div></section>'+cta()
page(Path('about'),'About','Learn about the RunBridge AI brand and product direction.',body)
body=hero('SUPPORT','Let’s get you<br><span>moving again.</span>','Start with the request details. Find the right guide. Keep credentials private.')
body+='<section class="container content-section"><div class="integration-grid">'+''.join(f'<a class="info-card linked-card" href="{url}"><h2>{title}</h2><p>{desc}</p><span class="text-link">Read guide →</span></a>' for title,desc,url in [('Getting started','Prepare your account configuration and understand the first request.','/docs/'),('Authentication','Check API keys, model access and server configuration.','/docs/authentication/'),('Request errors','Investigate errors, timeouts and safe retry behavior.','/docs/errors/')])+'</div></section>'+faq([('What should I include in a support report?','Include a timestamp with timezone, request ID, model ID, HTTP status and a minimal reproduction. Remove API keys, personal data and private input content.'),('A generation timed out. Should I retry?','Check the existing request or job status first. A timeout does not prove the generation was never started.'),('Where do I contact the RunBridge team?','Official support channels will be published when account access opens. This preview does not submit tickets or send messages.')])+cta()
page(Path('support'),'Support','Find troubleshooting guidance for RunBridge AI integrations.',body)
body=hero('CHANGELOG','See what’s<br><span>taking shape.</span>','Updates to the RunBridge AI website and developer experience.')
body+='<section class="container content-section changelog"><div class="change-date">September 16, 2026<span class="tag">Website preview</span></div><article><h2>A connected, multi-page RunBridge.</h2><p>The brand preview now includes a model catalog, individual model-family pages, pricing tools, solutions, enterprise planning and developer resources.</p><ul><li>Independent routes and shared site navigation.</li><li>Searchable model catalog with provider and capability filters.</li><li>Editable budget estimator and model pricing structure.</li><li>Developer guides, integration notes and original articles.</li></ul><div class="notice">This is a website update. It does not announce live API availability.</div><a class="text-link" href="/models/">Explore the catalog →</a></article></section>'+cta()
page(Path('changelog'),'Changelog','Follow RunBridge AI website updates.',body)
# Explicit 404 prevents missing routes from looking like a successful homepage.
page(Path('404'),'Page not found','Find your way back to RunBridge AI.',hero('404','This bridge<br><span>doesn’t lead anywhere.</span>','The page you requested could not be found.','<div class="hero-actions"><a class="button" href="/">Back to home →</a><a class="button secondary" href="/models/">Explore models</a></div>'))
(OUT/'404.html').write_text((OUT/'404/index.html').read_text())
print('Built',len(list(OUT.rglob('index.html'))),'independent pages.')
