"""Focused content additions for the primary navigation pages."""
def section(kicker,title,content,classes=''):
 return f'<section class="container content-section {classes}"><div class="section-top"><div><div class="eyebrow">{kicker}</div><h2>{title}</h2></div></div>{content}</section>'

def before_cta(body,content):
 return body.replace('<section class="page-cta">',content+'<section class="page-cta">',1)

def enhance(path,body):
 if path=='models':
  body=before_cta(body,section('FIND YOUR STARTING POINT','Choose the output. Then choose the model.','<div class="route-cards"><a href="/models/?type=text"><span>01 / TEXT</span><h3>Write, reason & code</h3><p>Compare answers on the same tasks. Check context needs, output quality and token costs.</p><b>Explore text models →</b></a><a href="/models/?type=image"><span>02 / IMAGE</span><h3>Make the idea visible</h3><p>Align resolution and quality settings. Review the model’s generation and editing inputs.</p><b>Explore image models →</b></a><a href="/models/?type=video"><span>03 / VIDEO</span><h3>Bring a story to motion</h3><p>Start with duration, aspect ratio and reference inputs. Plan for asynchronous generation.</p><b>Explore video models →</b></a></div>'))
 elif path=='pricing':
  body=before_cta(body,section('FROM ESTIMATE TO BUDGET','Count the whole workload.','<div class="cost-explanation"><div><h3>Text cost</h3><p>Input tokens × input rate<br>+ output tokens × output rate</p><span>Divide token counts by one million when your rates are quoted per 1M tokens.</span></div><div><h3>Image & video cost</h3><p>Billable output units<br>× the selected model’s unit rate</p><span>Check resolution, quality, duration and any additional model-specific charges.</span></div><div><h3>Monthly plan</h3><p>Cost per task<br>× expected monthly tasks</p><span>Include generation iterations and retries according to the applicable billing rules.</span></div></div><div class="content-note"><strong>Next step</strong><span>Choose your workload and document its assumptions before selecting a rate.</span><a href="/blog/plan-your-ai-budget/">Read the budget guide →</a></div>'))
 elif path=='solutions':
  body=before_cta(body,section('A PRACTICAL LAUNCH PATH','Bring one workflow into focus.','<div class="launch-steps"><article><span>01</span><h3>Scope the task</h3><p>Choose a repeatable user action and define what a useful result looks like.</p></article><article><span>02</span><h3>Compare candidates</h3><p>Test a small set of models on consistent prompts, inputs and output settings.</p></article><article><span>03</span><h3>Connect the product</h3><p>Add generation to your workflow with progress, retry and review states.</p></article><article><span>04</span><h3>Measure & improve</h3><p>Track task success, latency, cost and the cases that need human review.</p></article></div>'))
 elif path=='enterprise':
  body=before_cta(body,section('BEFORE THE FIRST CONVERSATION','A better brief. A clearer starting point.','<div class="enterprise-checklist"><div><h3>Workload & volume</h3><p>Your main use cases, expected calls per day and peaks in demand.</p></div><div><h3>Models & quality</h3><p>Required modalities, shortlisted providers and evaluation criteria.</p></div><div><h3>Data & operations</h3><p>Data sensitivity, location requirements and logging expectations.</p></div><div><h3>Commercial requirements</h3><p>Budget range, procurement process, timeline and support needs.</p></div></div><div class="center-action"><a class="button secondary" href="#enterprise-form">Prepare your project brief ↑</a></div>'))
 elif path=='docs':
  body=body.replace('<h2>1. Prepare your configuration</h2>','<div class="docs-start-links"><a href="/docs/authentication/"><strong>Authentication</strong><span>Keys & configuration →</span></a><a href="/docs/api-reference/"><strong>Request guide</strong><span>Text, image & video →</span></a><a href="/docs/errors/"><strong>Error handling</strong><span>Retries & timeouts →</span></a></div><h2>Before you start</h2><ul class="readable-list"><li>A server-side environment for your chosen language.</li><li>A provisioned account with its API key and base URL.</li><li>An exact model version ID and the schema it supports.</li></ul><h2>1. Prepare your configuration</h2>')
  body=body.replace('<h2>3. Review the response</h2>','<div class="content-note"><strong>Choose the correct client</strong><span>Python and JavaScript examples use the OpenAI SDK in a server environment. The cURL example sends an HTTP request directly.</span><a href="/integrations/">View integration setup →</a></div><h2>3. Review the response</h2>')
  body=body.replace('<div class="doc-next">','<h2>Before your first production request</h2><ul class="readable-list"><li>Set a request timeout and a bounded retry policy.</li><li>Log the model ID and request ID without recording secrets.</li><li>Review usage fields and confirm the selected model’s billing unit.</li><li>For job-based APIs, save the job ID before polling for results.</li></ul><div class="doc-next">',1)
 elif path=='integrations':
  guides=[('Python SDK','A server-side Python application.','Load your account key, endpoint and exact model ID from environment variables. Initialize your client once and send the request from your backend.','Handle exceptions at the application boundary and record a request identifier for investigation.','/docs/'),('JavaScript SDK','A server-side Node.js application.','Configure the client with your account endpoint and key. Keep secrets out of code bundled for the browser.','Return only the content your frontend needs. Set an application timeout and handle rejected requests.','/docs/?lang=javascript'),('cURL / HTTP','A direct request from a terminal or server.','Attach the bearer credential and Content-Type header, then send a JSON body that matches the selected model schema.','Inspect both HTTP status and response body. Do not paste a live credential into shared logs.','/docs/?lang=curl'),('Automation workflows','An HTTP request step in your workflow builder.','Use the platform’s credential mechanism for authorization, map your workflow inputs into the request body, and validate the response.','Keep the returned job ID for asynchronous requests. Avoid restarting a generation every time a workflow polls.','/docs/api-reference/'),('App builders','A builder that supports custom model endpoints.','Check that the builder accepts the account endpoint, model ID and authentication format. Confirm the specific modality is supported.','A text-model integration does not automatically support image or video request schemas.','/docs/api-reference/'),('Custom applications','Your own backend and application flow.','Separate the provider connection from your product logic. Store model configuration alongside the version of your workflow.','Define fallback behavior at the task level and compare results before changing models.','/docs/errors/')]
  content='<div class="setup-list">'
  for i,(name,environment,configure,check,link) in enumerate(guides):
   content+=f'<details class="setup-guide"'+(' open' if i==0 else '')+f'><summary><span class="setup-num">0{i+1}</span><strong>{name}</strong><span class="setup-expand">+</span></summary><div class="setup-body"><div><span>WHERE IT RUNS</span><p>{environment}</p></div><div><span>CONFIGURE</span><p>{configure}</p></div><div><span>VERIFY</span><p>{check}</p></div><a class="text-link" href="{link}">Open the matching guide →</a></div></details>'
  content+='</div>'
  body=before_cta(body,section('CONFIGURATION GUIDES','One connection, in your environment.',content))
 elif path=='blog':
  feature='<section class="container featured-story"><div class="featured-visual"><span>THE GENERATION WORKFLOW</span><strong>Think it.<br>Picture it.<br>Move it.</strong><span>TEXT → IMAGE → VIDEO</span></div><div class="featured-copy"><div class="eyebrow">FEATURED / DEVELOPMENT</div><h2>From a creative brief<br>to a connected workflow.</h2><p>Learn how to connect text, image and video stages while keeping context, review and job status under control.</p><a class="button secondary" href="/blog/design-a-multimodal-workflow/">Read the workflow guide ↗</a></div></section>'
  body=body.replace('<section class="container content-section"><div class="pill-tabs"',feature+'<section class="container content-section journal-list"><div class="journal-heading"><h2>All field notes</h2><label class="search-field"><span>⌕</span><input id="blog-search" type="search" placeholder="Search guides…" aria-label="Search blog articles"></label></div><div class="pill-tabs"',1)
  body=body.replace('<div class="article-grid">','<p class="results-label" id="blog-count" aria-live="polite">3 articles</p><div class="article-grid">',1)
  body=body.replace('</div></section><section class="page-cta">','</div><div class="empty-state" id="blog-empty" hidden><h3>No matching field notes.</h3><p>Try another search or reset the category.</p><button class="button secondary" id="blog-reset">Reset search</button></div></section><section class="page-cta">',1)
 elif path=='support':
  diagnostic=section('TROUBLESHOOT A REQUEST','Find the next step.','<div class="troubleshooter"><div><label for="support-issue">What are you seeing?</label><select id="support-issue"><option value="auth">Authentication or access error</option><option value="request">Invalid request or unsupported model</option><option value="rate">Rate limit or capacity limit</option><option value="timeout">Timeout or generation still running</option><option value="upstream">Server or upstream failure</option><option value="usage">Unexpected usage or charge</option></select><p>Use the exact response code and request ID from your application.</p></div><div id="support-guidance" aria-live="polite"></div></div>')
  body=body.replace('<section class="container content-section">',diagnostic+'<section class="container content-section">',1)
  report='''<div class="support-report"><div><h3>Make the issue reproducible.</h3><p>Copy this template, fill in the request details and remove sensitive inputs. Keep it ready for the official support channel when account access opens.</p><button class="button secondary" data-copy-target="support-template">Copy report template ⧉</button></div><pre id="support-template">Issue summary:
Timestamp and timezone:
Model ID:
HTTP status / error code:
Request or job ID:
Expected behavior:
Actual behavior:
Steps to reproduce:

Remove API keys and private content before sharing.</pre></div>'''
  body=before_cta(body,section('PREPARE A SUPPORT REPORT','The details that make a difference.',report))
 elif path=='changelog':
  latest='''<section class="container content-section changelog latest-release"><div class="change-date">September 16, 2026<span class="tag">Latest · Website</span></div><article><div class="eyebrow">NAVIGATION & DEVELOPER RESOURCES</div><h2>A direct path to every part of RunBridge.</h2><p>Documentation, integrations, the blog, changelog and support now have their own primary navigation entries, alongside models, pricing, solutions and enterprise.</p><ul><li>Expanded developer onboarding and environment-specific integration notes.</li><li>Search and category filters for the field notes.</li><li>Guided request troubleshooting and a copyable support-report template.</li><li>A responsive navigation layout with a clear current-page state.</li></ul><div class="release-links"><a href="/docs/">Explore documentation →</a><a href="/integrations/">Choose an integration →</a><a href="/support/">Find support →</a></div></article></section>'''
  body=body.replace('<section class="container content-section changelog">',latest+'<section class="container content-section changelog earlier-release">',1)
 return body
